version: '3.5'
services:
    app:
        build: .
        image: dairyease
        ports:            
            - 80:80
        volumes:
            - '/home/farooq/work/dairyease:/var/www/html'
        networks:
            - dairyease
        environment:        
            UID: 1000            
        depends_on:            
            - redis                
            # - mysql
        healthcheck:
            test: ["CMD", "chown", "-R" , "farooq:farooq", "/var/www/html"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'        
        networks:
            dairyease:
                aliases:
                  - dairyease-redis
        volumes:
          - 'dairyease_redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    # mysql:
    #     image: mysql:8.0        
    #     volumes:
    #         - carehub_mysql:/var/lib/mysql
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=audience
    #         - MYSQL_DATABASE=carehub
    #         - MYSQL_USER=carehub_portal
    #         - MYSQL_PASSWORD=audience
    #     ports:
    #       - '3306:3306'
    #     networks:
    #         carehub:
    #             aliases:
    #               - mysql-carehub
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links:
    #         - mysql
    #     environment:
    #         PMA_HOST: mysql-carehub
    #         PMA_PORT: 3306
    #     ports:
    #         - '8080:80'
    #     networks:
    #         carehub:
    #             aliases:
    #                 - phpmyadmin
networks:
    dairyease:
        driver: bridge
volumes:    
    dairyease_redis:
        driver: local
    # carehub_mysql:
    #     driver: local
